<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Firma.Data\Firma.Data.csproj" />
		<ProjectReference Include="..\Firma.Intranet.Services.Data\Firma.Intranet.Services.Data.csproj" />
	</ItemGroup>

</Project>