<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Firma.Data\Firma.Data.csproj" />
    <ProjectReference Include="..\Firma.Interfaces\Firma.Interfaces.csproj" />
    <ProjectReference Include="..\Firma.Services.Data\Firma.Services.Data.csproj" />
  </ItemGroup>

</Project>
